apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages
          image: us.gcr.io/airy-discovery-349015/messages
---
apiVersion: v1
kind: Service
metadata:
  name: messages-srv
spec:
  selector:
    app: messages
  ports:
    - name: messages
      protocol: TCP
      port: 4002
      targetPort: 4002
